### ISSUE TITLE
fix(pom): Maven life-cycle "site" (mvn site) fails with message "Could not connect to Central search"

### ISSUE THREAD

**Issue by joquijada** [gregswindle/maven-code-quality-pom#8]
**💡 TIP:** Select the ↖︎⎾ Preview ⏋ Tab above help read these instructions.

## 1. Issue type
>⌦ Type the letter "x" in the "checkbox" the best describe this issue.

- [x] __Defect:__  I encountered an error or detected a flaw.

## 2. User story summary

As a developer, 
I want to be able to run "mvn site" and "mvn site:run" to generate the reports that this module promises to deliver, 
So that I can ascertain the quality of my own Maven project.

## 3. Acceptance criteria

- [x] 1. The Maven site life-cycle (mvn site) runs successfully with no errors
- [x] 2. The Maven goal "site:run" (mvn site:run) runs successfully with no errors.

[icon-info-image]: ../docs/img/icons8/icon-info-50.png

**Comment by joquijada** [comment]
Greg,

In my local I tried the fix suggested [here](https://github.com/jeremylong/DependencyCheck/issues/978), and it worked. I will create a PR. Thaks.

**Comment by gregswindle** [comment]
@joquijada , thanks again for the PR and update! I've merged your changes into `master`.

🎉
